name: eight_app_weather_test
description: Test application Weather for 8app.ru
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.16.0'
  flutter: '>=2.10.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # Localization
  intl: 0.17.0

  # Annotation & Code-generation
  meta: 1.7.0
  json_annotation: ^4.3.0
  freezed_annotation: ^1.0.0

  # State manager & Inversion of Control
  bloc: ^8.0.3
  flutter_bloc: 8.0.1
  bloc_concurrency: 0.2.0

  # Utility & Helpers
  internet_connection_checker: ^0.0.1+3
  l: ^3.1.0
  responsive_framework: ^0.1.7
  dio:
  google_fonts: ^2.3.1
  retrofit: '>=3.0.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.10.1
  json_serializable: ^6.0.1
  freezed: ^1.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'


flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  enabled: true
